WITH CLASS_DATA AS (

SELECT DISTINCT
CLASS_II AS CLASS,
EMPLID,
STUDENT_TYPE_FINAL AS STUDENT_TYPE,
STUDENT_COLLEGE_CODE AS STUDENT_COLLEGE,
CLASSM_MEETING_TIME_START,

CASE
   WHEN (SUBSTR(CLASSM_MEETING_TIME_START,1,2)/1 + SUBSTR(CLASSM_MEETING_TIME_START,4,2)/60)-12 <= 0
   THEN (SUBSTR(CLASSM_MEETING_TIME_START,1,2)/1 + SUBSTR(CLASSM_MEETING_TIME_START,4,2)/60)
   ELSE (SUBSTR(CLASSM_MEETING_TIME_START,1,2)/1 + SUBSTR(CLASSM_MEETING_TIME_START,4,2)/60)-12
   END AS HOUR_INDEX_12,

SUBSTR(CLASSM_MEETING_TIME_START,1,2)/1 + SUBSTR(CLASSM_MEETING_TIME_START,4,2)/60 AS HOUR_INDEX_24,

CLASS_STDN_MTG_PAT

FROM IRAMASTER.EM_SU_FA_SP_R

WHERE CLASS_TERM = 2194
AND TRUNC(REPORT_DATE) = TRUNC(TO_DATE('23-Sep-2019','dd-mm-yyyy'))
AND ONLINE_COURSE IN ('Not_Online')
AND ENRL_UNITS_ATTEMPTED = 'I'
AND ENRL_STATUS_CD = 'E'
AND CLASS_SESSION_CODE = '1'

)

SELECT *
FROM CLASS_DATA
WHERE HOUR_INDEX_24 >= 8
AND HOUR_INDEX_24 <= 14.5
